spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: Video-App
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/video_spring_app
    username: postgres
    password: dung28011951
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
cloud:
  endpointUrl: https://s3.ap-southeast-2.amazonaws.com
  aws:
    credentials:
      access-key: AKIAQ3EGWTN6CXOVNZMO
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false
    bucket:
      name: movie-spring

